export default[
    {
        id: 1,
        title: "Frontend Developer",
        company: "Paytm",
        skills: ["Javascript", "React.js", "Node.js", "Tailwind CSS"],
        postedOn: "2023-12-7",
        experience: "Mid Level",
        location: "Hybrid",
        type: "Full Time",
        jobLink: "https://paytm.com/fse"
    },
    {
        id: 2,
        postedOn: '2023-12-2',
        title: "Frontend Developer",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript", "Nextjs", "Tailwind CSS"],
        jobLink: "https://www.amazon.jobs/en/",
      },
      {
        id: 3,
        postedOn: '2023-12-5',
        title: "Android Developer",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        jobLink: "https://facebook.com/careers",
      },
      {
        id: 4,
        postedOn: '2023-11-01',
        title: "Developer Advocate",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Netflix",
        companyUrl: "https://facebook.com",
        skills: ["web3", "Content Creation", "Community"],
        jobLink: "https://jobs.netflix.com/",
      },
] 